### PR TITLE
Add abi3audit check for stable ABI violations to CI

### PR DESCRIPTION
**Pull request by nicholasjng**
Only applies to CPython>=3.12.

### CODE REVIEW

**Comment by nicholasjng** [comment]
Nice, the wheel ABI tag comes out correct, and no ABI violations are found (although it would probably be hard to produce one with just the given example?).

**Comment by wjakob** [comment]
When compiling stable ABI wheels, are you passing `Py_LIMITED_API`? (Without that flag, nanobind will index into various version-specific data structures, but such a violation may not necessarily be found by an ABI audit that checks for the presence of disallowed symbols)

**Comment by nicholasjng** [comment]
I compile the nanobind .so with `-DPy_LIMITED_API=0x030?0000`, given via the selected ABI version here:

https://github.com/nicholasjng/nanobind-bazel/blob/97e3db2744d3f5da244a0846a0644ffb074b4880/helpers.bzl#L17-L22

I pass that as a `define` to `@nanobind//:nanobind` here:

https://github.com/nicholasjng/nanobind-bazel/blob/97e3db2744d3f5da244a0846a0644ffb074b4880/nanobind.BUILD#L33

which by default propagates to consuming rules. I do not, however, define the `Py_LIMITED_API` macro in the `setuptools.Extension`, for example in your `nanobind_example`, but that should not be an issue, since setuptools' C++ toolchain is not used by Bazel.

Does that seem correct?

**Comment by wjakob** [comment]
The first part sounds good, the second part I don't understand. In the `nanobind_example`, it's cmake that produces the commands that will eventually compile and link code, hence it is the component responsible for setting these flags. I don't think `setuptools` does anything interesting here besides, perhaps, choosing the name of the final wheel.

**Comment by nicholasjng** [comment]
Sorry, I meant on the `bazel` branch which you allowed me to push, that contains a setuptools+Bazel approach (though it's very rough).

**Comment by wjakob** [comment]
got it, thanks!

**Pull request merged**
